# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.5
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - sudo apt-get update
	# ArrayFire
  - sudo apt-get install libfreeimage-dev libatlas3gf-base libfftw3-dev cmake
  - wget http://ci.arrayfire.org/userContent/Linux/ArrayFire-no-gl-v3.4.2_Linux_x86_64.sh
  - ls -l
  - sudo chmod +x ArrayFire-no-gl-v3.4.2_Linux_x86_64.sh
  - sudo ./ArrayFire-no-gl-v3.4.2_Linux_x86_64.sh --exclude-subdir --prefix=/usr/local
	# Conda to install matplotlib
	- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
	- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION matplotlib
  - source activate test-environment
  - python setup.py install

before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Darwin" ]]; then JULIA="julia"; else JULIA="xvfb-run julia"; fi;
   $JULIA -e 'ENV["PYTHON"]=""; Pkg.clone(pwd()); Pkg.build("Shearlab"); Pkg.test("Shearlab"; coverage=true)';

after_success:
- julia -e 'cd(Pkg.dir("Shearlab")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
