# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  #- osx

julia:
  - 0.6
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - sudo apt-get update
  # ArrayFire
  - sudo apt-get install libfreeimage-dev libatlas3gf-base libfftw3-dev cmake
  - wget http://arrayfire.s3.amazonaws.com/3.4.2/ArrayFire-no-gl-v3.4.2_Linux_x86_64.sh
  - ls -l
  - sudo chmod +x ArrayFire-no-gl-v3.4.2_Linux_x86_64.sh
  - sudo ./ArrayFire-no-gl-v3.4.2_Linux_x86_64.sh --exclude-subdir --prefix=/usr/local

before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/

script:
  #- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  #- if [[ `uname` = "Darwin" ]]; then JULIA="julia"; else JULIA="xvfb-run julia"; fi;
   - LD_PRELOAD=${HOME}/.julia/v0.6/Conda/deps/usr/lib/libz.so
   - julia -e 'ENV["PYTHON"]="";Pkg.build("PyCall"); Pkg.build("PyPlot") ;Pkg.clone(pwd()); Pkg.build("Shearlab"); Pkg.test("Shearlab"; coverage=true)';

after_success:
- julia -e 'cd(Pkg.dir("Shearlab")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
